### ISSUE TITLE
A Meteor app that list ranked Meteor apps & their info (rank, packages, collections, meteor version) 

### ISSUE THREAD

**Issue by maxenceC** [ericdouglas/Meteor-Learning#50]
The following webapp features a list of the largest Meteor applications out there :

http://www.rankmeteor.com/

As well as featuring the most used packages : 

http://www.rankmeteor.com/packages

Disclaimer : I am hosting the app

**Comment by ericdouglas** [comment]
@maxenceC thank you! :smile:

**Comment by maxenceC** [comment]
@ericdouglas Thanks :+1:
