### ISSUE TITLE
Some links not working

### ISSUE THREAD

**Issue by zeroby0** [ericdouglas/Meteor-Learning#55]
Some of the links, like  madewith.meteor.com don't work any more. I didn't check for all the links, but few of them are broken, consider fixing.

**Comment by ericdouglas** [comment]
@zeroby0 ok, I'll check all links. Thanks for point this out :)

**Comment by ericdouglas** [comment]
## Verify links

- [ ] How to Collaborate
- [ ] Articles & Tutorials
- [ ] Books
- [ ] Built with Meteor
- [ ] Community
- [ ] Courses
- [ ] Learn with Code
- [ ] News
- [ ] Podcasts
- [ ] Screencasts
- [ ] Slides
- [ ] Talks
- [ ] More Useful Links

**Comment by zeroby0** [comment]
Hey,
I checked links and created a pull request, broken links were either removed or updated.
check commits in pr for more details :)

**Comment by ericdouglas** [comment]
@zeroby0 great work, thanks! :smile: :pray:
