### ISSUE TITLE
Learn Meteor book

### ISSUE THREAD

**Issue by epos** [ericdouglas/Meteor-Learning#60]
Hello,

Nice list! Could you please add the following book to the list? A specific web site is under construction for, and meanwhile the URL is:

http://arnaudweil.blogspot.com/2016/07/learn-meteor-book-available.html

Title: "Learn Meteor - Be ready for coding away next week using Meteor"

Thanks in advance,
Arnaud Weil

**Comment by ericdouglas** [comment]
@epos done! :smile:

**Comment by epos** [comment]
Thank you!-------- Message d'origine --------De : Eric Douglas <notifications@github.com> Date : 15/08/2016  11:03  (GMT+01:00) À : ericdouglas/Meteor-Learning <Meteor-Learning@noreply.github.com> Cc : Arnaud <commercial.weil@free.fr>, Mention <mention@noreply.github.com> Objet : Re: [ericdouglas/Meteor-Learning] Learn Meteor book (#60) 
@epos done! 😄 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ericdouglas/Meteor-Learning","title":"ericdouglas/Meteor-Learning","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ericdouglas/Meteor-Learning"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ericdouglas in #60: @epos done! :smile: "}],"action":{"name":"View Issue","url":"https://github.com/ericdouglas/Meteor-Learning/issues/60#issuecomment-239758528"}}}
