### ISSUE TITLE
The url is no longer valid

### ISSUE THREAD

**Issue by abduwaly** [ericdouglas/Meteor-Learning#71]
The second url below is no longer valid ( `README.md, Line:22` )

> This list was inspired by [this](https://github.com/jmcunningham/AngularJS-Learning) and [this](http://yauh.de/articles/376/best-learning-resources-for-meteorjs)! 

@ericdouglas , please have a look.

**Comment by distalx** [comment]
maybe start archiving links using `archive.is`?
